<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1612022663696' stop='1612022670312'>
    <name>Sample Test Suite</name>
    <title>Sample Test Suite</title>
    <test-cases>
        <test-case start='1612022663696' status='failed' stop='1612022667030'>
            <name>Test1</name>
            <title>Test1</title>
            <labels>
                <label name='epic' value='Login'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1612022667027' status='undefined'>
                    <name>Verify the Error Message</name>
                    <title>Verify the Error Message</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>ReferenceError: Status is not defined</message>
                <stack-trace>ReferenceError: Status is not defined
                    at Object.test (/Users/arunkumaraswamy/Documents/projects/Study/Puppeteer/JestPuppeteerAllure/functional-tests/src/tests/test1.spec.js:25:26)
                    at processTicksAndRejections (internal/process/next_tick.js:81:5)</stack-trace>
            </failure>
            <description type='text'>Start Assertion</description>
        </test-case>
        <test-case start='1612022667030' status='failed' stop='1612022670311'>
            <name>Test2</name>
            <title>Test2</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: expect(received).toEqual(expected) // deep equality
                
                Expected: "Incorrect username or passwo"
                Received: "Incorrect username or password."</message>
                <stack-trace>Error: expect(received).toEqual(expected) // deep equality
                
                Expected: "Incorrect username or passwo"
                Received: "Incorrect username or password."
                    at Object.test (/Users/arunkumaraswamy/Documents/projects/Study/Puppeteer/JestPuppeteerAllure/functional-tests/src/tests/test1.spec.js:49:23)
                    at processTicksAndRejections (internal/process/next_tick.js:81:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>